Feature/at sce UI admin operations
at-internship/at-sce-ui pull request #11
Opened 2021-03-10 21:38 UTC by MiltonNAR

We add changes to the files "admin.controller.js" and "at-sce-api.service.js" to integrate the POST method (create user)

2021-03-10 21:56 UTC, luishcastroc commented on src/controllers/admin.controller.js
> +    const {
no safety validations on this one? everything is not required?

2021-03-10 21:57 UTC, luishcastroc commented on src/services/at-sce-api.service.js
> +const AT_SCE_SERVICE_URI = process.env.AT_SCE_SERVICE_URI || `https://at-sce-api.herokuapp.com/api`;
this can be avoided by setting an env file in your local environment, prod url shouldn't be there and the env variable should be consumed instead.

2021-03-10 22:13 UTC, at-internship requested changes

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +   let users;
This variable is not needed

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +   //const userErrors = [];
Try to add  this kind of validations 

```
if (!user_firstName) {
    userErrors.push({ text: "Please Type a First Name." });
}
```

 ```
if (userErrors.length > 0) {
      res.render("admin/user/add-user", {
          userErrors,
          user_firstName,
          user_lastName,
          user_password,
          user_email,
          user_status,
      });
} else {
 // Call the service
```

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +        // Send data to microservice
Indent Code

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +            //Mensaje
// AT-SCE-API message

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +        // Redirect
Indent Code

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +
Remove this line

2021-03-10 22:13 UTC, at-internship commented on src/controllers/admin.controller.js
> +
Remove this line

2021-03-10 22:13 UTC, at-internship commented on src/services/at-sce-api.service.js
> +    console.log("Error: " + error.message);
console.log(`Error: ${error.message}`);

2021-03-10 22:13 UTC, at-internship commented on src/services/at-sce-api.service.js
> +    console.log("Error: " + error.message);
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2021-03-10 22:13 UTC, at-internship commented on src/services/at-sce-api.service.js
> +// Operation: Update USER - PUT /api/v1/users
Add a line here

2021-03-12 17:01 UTC, jaimeIxba approved these changes

2021-03-12 17:02 UTC, at-internship approved these changes
Looks good to me

2021-03-12 17:02 UTC, luishcastroc approved these changes

2021-03-12 17:03 UTC, merged