feature/AT-SCE-UI_AdminOperations_deleteUser
at-internship/at-sce-ui pull request #16
Opened 2021-03-12 23:16 UTC by FlavioAlejandro

I add changes to the files "admin.controller.js" and "at-sce-api.service.js" to integrate the delete method "deleteUser".

2021-03-14 03:45 UTC, at-internship approved these changes
Please review code  comments

2021-03-14 03:45 UTC, at-internship commented on src/controllers/admin.controller.js
> +      console.log("Resultado-->", result);
Comment this line

2021-03-14 03:45 UTC, at-internship commented on src/controllers/admin.controller.js
> +    console.log(request);
Comment this line

2021-03-14 03:45 UTC, at-internship commented on src/views/admin/user/add-users.hbs
> +<div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-4 mb-3 bg-white border-bottom box-shadow">
This file add-user.hbs should not be part of this PR

2021-03-16 13:00 UTC, DianaArceoSuarez approved these changes

2021-03-16 14:39 UTC, MiltonNAR approved these changes

2021-03-16 15:10 UTC, jaimeIxba approved these changes

2021-03-16 15:17 UTC, AT-ivillamil approved these changes

2021-03-16 15:40 UTC, irvingesp2190 approved these changes

2021-03-16 15:44 UTC, at-internship requested changes

2021-03-16 15:44 UTC, at-internship commented on src/views/admin/user/add-users.hbs
> +<div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-4 mb-3 bg-white border-bottom box-shadow">
Delete this file

2021-03-16 16:16 UTC, FlavioAlejandro commented on src/views/admin/user/add-users.hbs
> +<div class="d-flex flex-column flex-md-row align-items-center p-2 px-md-4 mb-3 bg-white border-bottom box-shadow">
Done

2021-03-16 16:19 UTC, at-internship approved these changes
Approved

2021-03-16 16:28 UTC, merged