feature/AT-SCE-UI_SaveOperation
at-internship/at-sce-ui pull request #22
Opened 2021-03-29 19:21 UTC by jaimeIxba

We add changes to the files "at-sce.controller.js", "at-sce-util.js", "calculator.hbs" and "at-sce-api.service.js" to integrate the POST method (create history).

2021-03-29 21:46 UTC, at-internship requested changes

2021-03-29 21:46 UTC, at-internship commented on src/config/passport.js
>  // Constants
what is the change on this file?

2021-03-29 21:46 UTC, at-internship commented on src/controllers/at-sce.controller.js
> +      userErrors.push({ text: "Empty Field. " });
Try to add more descriptive message

2021-03-29 21:46 UTC, at-internship commented on src/controllers/at-sce.controller.js
> +        total: total,
don't you think we also need parseFloat here?

2021-03-30 00:20 UTC, DianaArceoSuarez approved these changes

2021-03-30 02:14 UTC, at-internship approved these changes
Approved

2021-03-30 14:18 UTC, FlavioAlejandro approved these changes

2021-03-30 14:40 UTC, AT-ivillamil approved these changes

2021-03-30 14:51 UTC, merged