Feature/at sce UI templates admin
at-internship/at-sce-ui pull request #6
Opened 2021-03-04 21:42 UTC by MiltonNAR

2021-03-04 22:14 UTC, at-internship requested changes

2021-03-04 22:14 UTC, at-internship commented on src/views/admin/index.hbs
> +           <button type="button" class="btn btn-primary"> User</button>
`<a class="btn btn-primary" href="/admin/user">&raquo; Users</a>`

2021-03-04 22:15 UTC, at-internship commented on src/views/admin/index.hbs
> +           <button type="button" class="btn btn-primary"> User</button>
you can follow this view as reference https://github.com/at-internship/at-sso-ui/blob/develop/src/views/admin/index.hbs

2021-03-05 00:16 UTC, at-internship commented
Approved

2021-03-05 00:17 UTC, at-internship approved these changes
Approved

2021-03-05 00:29 UTC, irvingesp2190 approved these changes

2021-03-05 14:34 UTC, luishcastroc approved these changes

2021-03-05 14:39 UTC, merged